lib_name = "libalbatross_base.so"
#adb_path=
#jni_libs=

#albatross-java/app_agent/build/outputs/apk/release/xxxxx.apk
#agent_dir=

#albatross-java/app_agent/build/outputs/apk/release/xxxx.apk
#system_server_agent_file=

#app_agent_file=
#albatross_class_name=
#clear_history_launch=
#albatross_agent_class=
#albatross_register_func
#system_server_agent_dst=
#app_agent_dst
#app_injector_dir
#support_abi_list
#abi_lib_names=
#server_dst_path=
#lib_path=
#server_port=
#system_server_address=
#system_server_init_class=